FROM nginx:1.21.0-alpine

# Add static assets so they dont need to go through FPM
ADD src/web/ /opt/aligent-project/web/

# Configure nginx
ADD docker/nginx/default.conf /etc/nginx/conf.d/default.conf
ADD docker/nginx/aligent-project-fcgi.conf /etc/nginx/aligent-project-fcgi.conf
