# docker-compose file to include when creating the dev environment
services:
  fpm:
    environment:
      PHP_DEV: "yes"
    volumes:
      - ./src:/opt/aligent-project

  nginx:
    volumes:
      - ./src/web:/opt/aligent-project/web
