version: "3.9"
services:
  fpm:
    environment:
      PHP_DEV: "yes"
    build:
      context: .
      dockerfile: ./Dockerfile-fpm

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile-nginx
    ports:
      - 8080:80/tcp
